
package pkg25112022_kiemtra;

import java.awt.Font;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FORMAI
 */
public class QuanLyGui extends javax.swing.JFrame {

    DanhSachDichVuChoThue dsdvct;
    DefaultTableModel model;
    int i;
    DecimalFormat df= new DecimalFormat("#,###,###.0");
    public QuanLyGui() {
        initComponents();
        myInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboLoaiThue = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaXe = new javax.swing.JTextField();
        txtNgayThue = new javax.swing.JTextField();
        txtSoGioThue = new javax.swing.JTextField();
        txtLoaiXe = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        txtSoNgayThue = new javax.swing.JTextField();
        txtDKBL = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        butThemMoi = new javax.swing.JButton();
        butInDS = new javax.swing.JButton();
        butTimXe = new javax.swing.JButton();
        butXoaXe = new javax.swing.JButton();
        butDocFile = new javax.swing.JButton();
        butInDSCD = new javax.swing.JButton();
        txtTongTienThue = new javax.swing.JTextField();
        butTongTien = new javax.swing.JButton();
        butCapNhat = new javax.swing.JButton();
        butSapXep = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153), 3), "Cho Thuê Xe", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(204, 51, 0))); // NOI18N

        comboLoaiThue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thuê Theo Giờ", "Thuê Theo Ngày", " " }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Mã Xe");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Số Giờ Thuê");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Ngày Thuê");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Đơn Giá");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Loại Xe");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Số Ngày Thuê");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Điều Kiện Bằng");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtSoGioThue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoGioThueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(comboLoaiThue, 0, 200, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSoGioThue))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMaXe, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(txtNgayThue))))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLoaiXe, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(txtDonGia)
                            .addComponent(txtSoNgayThue))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(258, 258, 258))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtDKBL, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(231, 231, 231))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboLoaiThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoGioThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoNgayThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDKBL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MaXe", "LoaiXe", "NgayThue", "DonGia", "DKBangLai", "SoGioThue", "SoNgayThue", "ThanhTien"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 153, 153))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(0, 102, 102));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        butThemMoi.setForeground(new java.awt.Color(0, 102, 102));
        butThemMoi.setText("Thêm Mới");
        butThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butThemMoiActionPerformed(evt);
            }
        });

        butInDS.setForeground(new java.awt.Color(0, 102, 102));
        butInDS.setText("In Danh Sách");
        butInDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butInDSActionPerformed(evt);
            }
        });

        butTimXe.setForeground(new java.awt.Color(0, 102, 102));
        butTimXe.setText("Tìm Xe");
        butTimXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTimXeActionPerformed(evt);
            }
        });

        butXoaXe.setForeground(new java.awt.Color(0, 102, 102));
        butXoaXe.setText("Xóa Xe");
        butXoaXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butXoaXeActionPerformed(evt);
            }
        });

        butDocFile.setForeground(new java.awt.Color(0, 102, 102));
        butDocFile.setText("Đọc File");
        butDocFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butDocFileMouseClicked(evt);
            }
        });
        butDocFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDocFileActionPerformed(evt);
            }
        });

        butInDSCD.setForeground(new java.awt.Color(0, 102, 102));
        butInDSCD.setText("In DS Theo Giờ");
        butInDSCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butInDSCDActionPerformed(evt);
            }
        });

        butTongTien.setForeground(new java.awt.Color(0, 102, 102));
        butTongTien.setText("Tổng Tiền Cho Thuê Xe");
        butTongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTongTienActionPerformed(evt);
            }
        });

        butCapNhat.setForeground(new java.awt.Color(0, 102, 102));
        butCapNhat.setText("Cập nhật");
        butCapNhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butCapNhatMouseClicked(evt);
            }
        });
        butCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCapNhatActionPerformed(evt);
            }
        });

        butSapXep.setForeground(new java.awt.Color(0, 102, 102));
        butSapXep.setText("Sắp Xếp");
        butSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSapXepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtTongTienThue))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(butDocFile, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(butXoaXe, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(butThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(butInDS)
                                    .addComponent(butInDSCD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(butCapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(butTimXe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(butSapXep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(butTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(butTongTien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTongTienThue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(butThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(butInDS, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(butCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(butTimXe, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(butXoaXe, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(butDocFile, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(butInDSCD, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(butSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSoGioThueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoGioThueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoGioThueActionPerformed

    private void butThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butThemMoiActionPerformed
        // TODO add your handling code here:
        if(comboLoaiThue.getSelectedIndex()==0) {
            ThueTheoGio ttg= nhapTTG();
            dsdvct.themVaoDs(ttg);
            themVaoTable(ttg);
        } else {
            ThueTheoNgay ttn= nhapTTN();
            dsdvct.themVaoDs(ttn);
            themVaoTable(ttn);
        }
        txtDKBL.setText("");
        txtMaXe.setText("");
        txtNgayThue.setText("");
        txtDonGia.setText("");
        txtSoGioThue.setText("");
        txtLoaiXe.setText("");
        txtSoNgayThue.setText("");
        txtTongTienThue.setText("");
    }//GEN-LAST:event_butThemMoiActionPerformed

    private void butDocFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDocFileActionPerformed
        
        try {
            // TODO add your handling code here:
            FileReader fr= new FileReader("input.txt");
            BufferedReader br= new BufferedReader(fr);
            String line="";
            while(true) {
                line=br.readLine();
                if(line==null) break;
                String st[]=line.split(",");
                String maXe=st[0];
                String loaiXe=st[1];
                Date ngayChoThue=chuyenChuoiThanhNgay(st[2]);
                double donGia=Double.parseDouble(st[3]);
                String dkbl=st[4];
                double soGioThue=Double.parseDouble(st[5]);
                double soNgayThue=Double.parseDouble(st[6]);
                if(soNgayThue==0) {
                    ThueTheoGio ttg= new ThueTheoGio(soGioThue, maXe, loaiXe, ngayChoThue, donGia, dkbl);
                    dsdvct.themVaoDs(ttg);
                    themVaoTable(ttg);
                } else {
                    ThueTheoNgay ttn= new ThueTheoNgay(soNgayThue, maXe, loaiXe, ngayChoThue, donGia, dkbl);
                    dsdvct.themVaoDs(ttn);
                    themVaoTable(ttn);
                }
               
            }
            fr.close();
            br.close();
        } catch (IOException ex) {
            Logger.getLogger(QuanLyGui.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    }//GEN-LAST:event_butDocFileActionPerformed

    private void butInDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butInDSActionPerformed
        // TODO add your handling code here:
        xoaBang();
        for (DichVuThue dvt : dsdvct.arr) {
            themVaoTable(dvt);
        }
        txtTongTienThue.setText("");
    }//GEN-LAST:event_butInDSActionPerformed

    private void butTimXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTimXeActionPerformed
        // TODO add your handling code here:
        DichVuThue dvt= dsdvct.timXe(txtLoaiXe.getText());
        if(dvt!=null) {
            xoaBang();
            themVaoTable(dvt);
        } else {
            JOptionPane.showMessageDialog(null, "Tim kiem that bai!!");
        }
        txtTongTienThue.setText("");
    }//GEN-LAST:event_butTimXeActionPerformed

    private void butXoaXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butXoaXeActionPerformed
        // TODO add your handling code here:
        String maXe=txtMaXe.getText();
        if(dsdvct.xoaTheoMaXe(maXe)) {
            xoaBang();
            for (DichVuThue dvt : dsdvct.arr) {
                themVaoTable(dvt);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Xoa that bai!!");
        }
        txtTongTienThue.setText("");
    }//GEN-LAST:event_butXoaXeActionPerformed

    private void butTongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTongTienActionPerformed
        // TODO add your handling code here:
        for (DichVuThue dvt : dsdvct.arr) {
        txtTongTienThue.setText(String.valueOf(df.format(dsdvct.tinhTongTien())));    
        }
        
    }//GEN-LAST:event_butTongTienActionPerformed

    private void butInDSCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butInDSCDActionPerformed
        // TODO add your handling code here:
        xoaBang();
        for (DichVuThue dvt : dsdvct.inDSThueChiDinhGio()) {
            
            themVaoTable(dvt);
        }
    }//GEN-LAST:event_butInDSCDActionPerformed

    private void butCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCapNhatActionPerformed
        // TODO add your handling code here:
        
//        model.setValueAt(txtMaXe.getText(), i, 0);
//        model.setValueAt(txtLoaiXe.getText(), i, 1);
//        model.setValueAt(txtDonGia.getText(), i, 2);
//        model.setValueAt(txtNgayThue.getText(), i, 3);
//        model.setValueAt(txtDKBL.getText(),i, 4);
//        model.setValueAt(txtSoGioThue.getText(), i, 5);
//        model.setValueAt(txtSoNgayThue.getText(), i, 6);
//        model.setValueAt(comboLoaiThue.getSelectedItem().toString(), i,7);
        i = jTable1.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(null, "Ban chua chon dong de cap nhat!!");
        } else { 
        model.setValueAt(txtMaXe.getText(), i, 0);
        model.setValueAt(txtLoaiXe.getText(), i, 1);
        model.setValueAt(txtNgayThue.getText(), i, 2);
        model.setValueAt(txtDonGia.getText(), i, 3);
        model.setValueAt(txtDKBL.getText(),i, 4);
        model.setValueAt(txtSoGioThue.getText(), i, 5);
        model.setValueAt(txtSoNgayThue.getText(), i, 6);
            DichVuThue dvt= dsdvct.arr.get(i);
            if(dvt instanceof ThueTheoGio) {
                dvt.setMaXe(txtMaXe.getText());
                dvt.setLoaiXe(txtLoaiXe.getText());
                dvt.setNgayThue(chuyenChuoiThanhNgay(txtNgayThue.getText()));
                dvt.setDonGia(Double.parseDouble(txtDonGia.getText()));
                dvt.setDieuKienBang(txtDKBL.getText());
                ((ThueTheoGio) dvt).setSoGioThue(Double.parseDouble(txtSoGioThue.getText()));
            } else {
                ThueTheoNgay ttn= (ThueTheoNgay) dvt;
                ttn.setMaXe(txtMaXe.getText());
                ttn.setLoaiXe(txtLoaiXe.getText());
                ttn.setNgayThue(chuyenChuoiThanhNgay(txtNgayThue.getText()));
                ttn.setDonGia(Double.parseDouble(txtDonGia.getText()));
                ttn.setDieuKienBang(txtDKBL.getText());
                ttn.setSoNgayThue(Double.parseDouble(txtSoNgayThue.getText()));
            }
        }
    }//GEN-LAST:event_butCapNhatActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        i= jTable1.getSelectedRow();
        
        if(evt.getClickCount()==2) {
            txtMaXe.setText(model.getValueAt(i, 0).toString());
            txtLoaiXe.setText(model.getValueAt(i, 1).toString());
            txtNgayThue.setText(model.getValueAt(i, 2).toString());
            txtDonGia.setText(model.getValueAt(i, 3).toString());
            txtDKBL.setText(model.getValueAt(i, 4).toString());
            txtSoGioThue.setText(model.getValueAt(i,5).toString());
            txtSoNgayThue.setText(model.getValueAt(i, 6).toString());
            comboLoaiThue.setSelectedItem(model.getValueAt(i, 7));
//            txtTongTienThue.setText(model.getValueAt(i, 8).toString());  
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void butSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSapXepActionPerformed
        // TODO add your handling code here:
        
        try {
            FileWriter fw= new FileWriter(new File("output.txt"));
            BufferedWriter bw= new BufferedWriter(fw);
            dsdvct.SapXep();
            for (DichVuThue dvt : dsdvct.arr) {
                if(dvt instanceof ThueTheoGio) {
                fw.write(dvt.getMaXe()+"\t"+dvt.getLoaiXe()+"\t"+chuyenNgayThanhChuoi(dvt.getNgayThue())+"\t"+String.valueOf(dvt.getDonGia())+"\t"+dvt.getDieuKienBang()+"\t"+String.valueOf(((ThueTheoGio) dvt).getSoGioThue())+"\t"+""+"\t"+df.format(dvt.tinhThanhTien())+"\n");
            } else {
                    ThueTheoNgay dvt2=(ThueTheoNgay) dvt;
                    fw.write(dvt2.getMaXe()+"\t"+dvt2.getLoaiXe()+"\t"+chuyenNgayThanhChuoi(dvt2.getNgayThue())+"\t"+String.valueOf(dvt2.getDonGia())+"\t"+dvt.getDieuKienBang()+"\t"+""+"\t"+String.valueOf(dvt2.getSoNgayThue()+"\t"+df.format(dvt2.tinhThanhTien()))+"\n");
                }
            }
            JOptionPane.showMessageDialog(null, "Da sap xep xong, hay vao thu muc de kiem tra!!");
        fw.close();
        bw.close();
        } catch (IOException ex) {
            Logger.getLogger(QuanLyGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_butSapXepActionPerformed

    private void butCapNhatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butCapNhatMouseClicked
        // TODO add your handling code here:

        
    }//GEN-LAST:event_butCapNhatMouseClicked

    private void butDocFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butDocFileMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_butDocFileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butCapNhat;
    private javax.swing.JButton butDocFile;
    private javax.swing.JButton butInDS;
    private javax.swing.JButton butInDSCD;
    private javax.swing.JButton butSapXep;
    private javax.swing.JButton butThemMoi;
    private javax.swing.JButton butTimXe;
    private javax.swing.JButton butTongTien;
    private javax.swing.JButton butXoaXe;
    private javax.swing.JComboBox<String> comboLoaiThue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDKBL;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtLoaiXe;
    private javax.swing.JTextField txtMaXe;
    private javax.swing.JTextField txtNgayThue;
    private javax.swing.JTextField txtSoGioThue;
    private javax.swing.JTextField txtSoNgayThue;
    private javax.swing.JTextField txtTongTienThue;
    // End of variables declaration//GEN-END:variables
    public ThueTheoGio nhapTTG() {
        String maXe=txtMaXe.getText();
        String loaiXe=txtLoaiXe.getText();
        Date ngayThue=chuyenChuoiThanhNgay(txtNgayThue.getText());
        double donGia=Double.parseDouble(txtDonGia.getText());
        String dkbl=txtDKBL.getText();
        double soGioThue=Double.parseDouble(txtSoGioThue.getText());
        ThueTheoGio ttg= new ThueTheoGio(soGioThue, maXe, loaiXe, ngayThue, donGia, dkbl);
        return ttg;
    }
    public ThueTheoNgay nhapTTN() {
        String maXe=txtMaXe.getText();
        String loaiXe=txtLoaiXe.getText();
        Date ngayThue=chuyenChuoiThanhNgay(txtNgayThue.getText());
        double donGia=Double.parseDouble(txtDonGia.getText());
        String dkbl=txtDKBL.getText();
        double soNgayThue=Double.parseDouble(txtSoNgayThue.getText());
        ThueTheoNgay ttn= new ThueTheoNgay(soNgayThue, maXe, loaiXe, ngayThue, donGia, dkbl);
        return ttn;
    }
    public void themVaoTable(DichVuThue dvt) {
        if(dvt instanceof ThueTheoGio) {
            model.addRow(new Object[] {dvt.getMaXe(),dvt.getLoaiXe(),chuyenNgayThanhChuoi(dvt.getNgayThue()),dvt.getDonGia(),dvt.getDieuKienBang(),((ThueTheoGio) dvt).getSoGioThue(),"",df.format(dvt.tinhThanhTien())});
        } else {
            ThueTheoNgay ttn=(ThueTheoNgay) dvt;
            model.addRow(new Object[] {ttn.getMaXe(),ttn.getLoaiXe(),chuyenNgayThanhChuoi(ttn.getNgayThue()),dvt.getDonGia(),dvt.getDieuKienBang(),"",ttn.getSoNgayThue(),df.format(ttn.tinhThanhTien())});
        }
    }
    private void myInit() {
        setLocationRelativeTo(null);
        setTitle("Dich Vu Cho Thue Xe");
        dsdvct = new DanhSachDichVuChoThue();
        model = (DefaultTableModel) jTable1.getModel();//phai co
        jTable1.setModel(model);
        jTable1.setRowHeight(22);
//       
    }
    public void xoaBang() {
        for (int i=jTable1.getRowCount(); i >0 ; i--) {
            model.removeRow(i-1);
        }
        
    }

    private Date chuyenChuoiThanhNgay(String text) {
        try {
            return new SimpleDateFormat("dd/MM/yy").parse(text);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        return null;
    }
    private String chuyenNgayThanhChuoi(Date d) {
        return new SimpleDateFormat("dd/MM/yy").format(d);
    }
}
