/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jtable_file;

import java.awt.Font;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FORMAI
 */
public class QuanLiNhanVien extends javax.swing.JFrame {
DanhSachNhanVien dsnv;//Core item
DefaultTableModel model; //Core item

    /**
     * Creates new form QuanLiNhanVien
     */
public NhanVien nhapTT() {
    NhanVien nv= new NhanVien(txtCMND.getText(), txtHoTen.getText(), chuyenChuoiThanhNgay(txtNgaySinh.getText()), Float.parseFloat(txtHSL.getText()));
    return nv;
}
public void ThemVaoTable(NhanVien nv) {
    model.addRow(new Object[] {nv.getCMND(), nv.getHoTen(), chuyenNgayThanhChuoi(nv.getNgaySinh()),nv.getHSL(),nv.tinhLuong()});
    
}
public void xoaBang() {
    for (int i = jTable1.getRowCount(); i >0 ; i--) {
        model.removeRow(i-1);
    }
}

    public QuanLiNhanVien() {
        initComponents();
        myInit();
    }
    public String chuyenNgayThanhChuoi(Date d) {
        return new SimpleDateFormat("dd/MM/yy").format(d);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCMND = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        txtHSL = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        butThemMoi = new javax.swing.JButton();
        butInDS = new javax.swing.JButton();
        butDocFile = new javax.swing.JButton();
        butSapXep = new javax.swing.JButton();
        butInNamSinh = new javax.swing.JButton();
        butXoaCMND = new javax.swing.JButton();
        butTimCMND = new javax.swing.JButton();
        butCapNhatCMND = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153), 3), "Thong Tin Nhan Vien", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 14), new java.awt.Color(204, 0, 0))); // NOI18N

        jLabel1.setText("CMND");

        jLabel2.setText("Ho Ten");

        jLabel3.setText("Ngay Sinh");

        jLabel4.setText("HSL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtHSL))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNgaySinh))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtHoTen))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtCMND, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHSL, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CMND", "Ten", "NgaySinh", "HSLuong", "Luong"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        butThemMoi.setText("Them Moi");
        butThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butThemMoiActionPerformed(evt);
            }
        });

        butInDS.setText("In Danh Sach");
        butInDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butInDSActionPerformed(evt);
            }
        });

        butDocFile.setText("Doc File");
        butDocFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDocFileActionPerformed(evt);
            }
        });

        butSapXep.setText("Sap Xep");
        butSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSapXepActionPerformed(evt);
            }
        });

        butInNamSinh.setText("In Nam Sinh Trung Nhau");

        butXoaCMND.setText("Xoa Theo CMND");
        butXoaCMND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butXoaCMNDActionPerformed(evt);
            }
        });

        butTimCMND.setText("Tim Theo CMND");
        butTimCMND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTimCMNDActionPerformed(evt);
            }
        });

        butCapNhatCMND.setText("Cap Nhat Theo CMND");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(butThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112)
                        .addComponent(butInDS, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112)
                        .addComponent(butDocFile, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139)
                        .addComponent(butSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(butXoaCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(418, 418, 418)
                        .addComponent(butTimCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(butCapNhatCMND)
                        .addGap(62, 62, 62)
                        .addComponent(butInNamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butInDS, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butDocFile, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butXoaCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butTimCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butCapNhatCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butInNamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butThemMoiActionPerformed
        // TODO add your handling code here:
        NhanVien nv=nhapTT();
	dsnv.themVaoDS(nv);
        ThemVaoTable(nv);
    }//GEN-LAST:event_butThemMoiActionPerformed

    private void butInDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butInDSActionPerformed
        // TODO add your handling code here:
        xoaBang();
        for (NhanVien nv : dsnv.arr) {
            
            ThemVaoTable(nv);
        }
        
    }//GEN-LAST:event_butInDSActionPerformed

    private void butDocFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDocFileActionPerformed
    try {
        // TODO add your handling code here:
        FileReader fr= new FileReader("input.txt");
        BufferedReader br= new BufferedReader(fr);
        String line="";
        while(true) {
            line= br.readLine();
            if(line==null) {
                break;
                }
            String st[]= line.split(",");
            String CMND=st[0];
            String hoTen=st[1];
            Date ngaySinh=chuyenChuoiThanhNgay(st[2]);
            float HSL=Float.parseFloat(st[3]);
            NhanVien nv= new NhanVien(CMND, hoTen, ngaySinh, HSL);
            dsnv.themVaoDS(nv);
            ThemVaoTable(nv);
//        fr.close();
//        br.close();
        }
        fr.close();
        br.close();
    } catch (IOException ex) {
        Logger.getLogger(QuanLiNhanVien.class.getName()).log(Level.SEVERE, null, ex);
    }
           
    }//GEN-LAST:event_butDocFileActionPerformed

    private void butTimCMNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTimCMNDActionPerformed
        // TODO add your handling code here:
        NhanVien nv= dsnv.timTheoCMND(txtCMND.getText());
        if(nv!=null) {
            xoaBang();
            ThemVaoTable(nv);
        } else {
            JOptionPane.showMessageDialog(null, "Ko tim thay!!");
        }
    }//GEN-LAST:event_butTimCMNDActionPerformed

    private void butXoaCMNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butXoaCMNDActionPerformed
        // TODO add your handling code here:
        xoaBang();
       dsnv.xoaTheoCMND(txtCMND.getText());
        for (NhanVien nv : dsnv.arr) {
            ThemVaoTable(nv);
        }
    }//GEN-LAST:event_butXoaCMNDActionPerformed

    private void butSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSapXepActionPerformed
    try {
        // TODO add your handling code here:
        FileWriter fw= new FileWriter(new File("output.txt"));
        BufferedWriter bw= new BufferedWriter(fw);
        dsnv.sapXepHSL();
        for (NhanVien nv : dsnv.arr) {
//            fw.write(nv.getCMND()+"\n");
//            fw.write(nv.getHoTen()+"\n");
//            fw.write(chuyenNgayThanhChuoi(nv.getNgaySinh())+"\n");
//            fw.write(String.valueOf(nv.getHSL())+"\n");
//              fw.write(String.valueOf(nv.tinhLuong())+"\n");
    fw.write(nv.getCMND()+"\t"+nv.getHoTen()+"\t"+chuyenNgayThanhChuoi(nv.getNgaySinh())+"\t"+String.valueOf(nv.getHSL())+"\t"+String.valueOf(nv.tinhLuong())+"\n");
        }
        JOptionPane.showMessageDialog(null, "Da sap xep xong, hay vao thu muc de kiem tra!!");
        fw.close();
        bw.close();
    } catch (IOException ex) {
        Logger.getLogger(QuanLiNhanVien.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_butSapXepActionPerformed

    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLiNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLiNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLiNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLiNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLiNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butCapNhatCMND;
    private javax.swing.JButton butDocFile;
    private javax.swing.JButton butInDS;
    private javax.swing.JButton butInNamSinh;
    private javax.swing.JButton butSapXep;
    private javax.swing.JButton butThemMoi;
    private javax.swing.JButton butTimCMND;
    private javax.swing.JButton butXoaCMND;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtHSL;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtNgaySinh;
    // End of variables declaration//GEN-END:variables

    private void myInit() {
        setTitle("QUAN LI NHAN VIEN");
        setSize(1100,650);
        dsnv= new DanhSachNhanVien();
        setLocationRelativeTo(null);
        model=(DefaultTableModel) jTable1.getModel();
        jTable1.setModel(model);
        jTable1.setRowHeight(22);
        jTable1.setFont(new Font("Consolas", 0, 20));
        jTable1.getTableHeader().setFont(new Font("Consolas", 1, 22));
    }

    private Date chuyenChuoiThanhNgay(String text) {
        try {
            return new SimpleDateFormat("dd/MM/yy").parse(text);
        } catch (ParseException e) {
            return null;
        }
    }
    
}
