/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dethi3;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FORMAI
 */
public class QuanLiBN extends javax.swing.JFrame {

    DSBenhNhan dsbn;
    DefaultTableModel model;

    public QuanLiBN() {
        initComponents();
        myInit();
    }

    public BNNoiTru nhapBNNoi() {
        String maBN = txtMaBN.getText();
        String hoTen = txtHoTen.getText();
        Date ngayVao = chuyenChuoiThanhNgay(txtNgayVV.getText());
        double tienThuoc = Double.parseDouble(txtTienThuoc.getText());
        double phiNgay = Double.parseDouble(txtPhiNgay.getText());
        Date ngayRa = chuyenChuoiThanhNgay(txtNgayRV.getText());
        BNNoiTru bnnoi = new BNNoiTru(phiNgay, ngayRa, maBN, hoTen, ngayVao, tienThuoc);
        return bnnoi;
    }

    public BNNgoaiTru nhapBNNgoai() {
        String maBN = txtMaBN.getText();
        String hoTen = txtHoTen.getText();
        Date ngayVao = chuyenChuoiThanhNgay(txtNgayVV.getText());
        double tienThuoc = Double.parseDouble(txtTienThuoc.getText());
        double phiKham = Double.parseDouble(txtPhiKham.getText());
        double phiXN = Double.parseDouble(txtPhiXN.getText());
        BNNgoaiTru bnngoai = new BNNgoaiTru(phiKham, phiXN, maBN, hoTen, ngayVao, tienThuoc);
        return bnngoai;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboBN = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPhiNgay = new javax.swing.JTextField();
        txtNgayRV = new javax.swing.JTextField();
        txtPhiKham = new javax.swing.JTextField();
        txtPhiXN = new javax.swing.JTextField();
        txtNgayVV = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txtMaBN = new javax.swing.JTextField();
        txtTienThuoc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        butThemMoi = new javax.swing.JButton();
        butTongVienPhi = new javax.swing.JButton();
        txtTongVP = new javax.swing.JTextField();
        butTimBN = new javax.swing.JButton();
        butDSBNNgoai = new javax.swing.JButton();
        butDocFile = new javax.swing.JButton();
        butInDS = new javax.swing.JButton();
        butXoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboBN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BN Ngoại Trú", "BN Nội Trú", " " }));

        jLabel1.setText("Mã BN");

        jLabel2.setText("Họ Tên");

        jLabel3.setText("Ngày Vào Viện");

        jLabel4.setText("Tiền Thuốc");

        jLabel5.setText("Ngày Ra Viện");

        jLabel6.setText("Phí Xét Nghiệm");

        jLabel7.setText("Phí Khám");

        jLabel8.setText("Phí Ngày");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(comboBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNgayVV, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaBN, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTienThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPhiXN, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPhiNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgayRV, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhiKham, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgayVV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhiNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaBN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgayRV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhiKham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTienThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtPhiXN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MaBN", "Ho & Ten", "Ngay VaoVien", "Tien Thuoc", "Phi Kham", "Phi XN", "Phi Ngay", "Ngay RaVien", "VienPhi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true, true, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        butThemMoi.setText("Them Moi");
        butThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butThemMoiActionPerformed(evt);
            }
        });

        butTongVienPhi.setText("Tong Vien Phi");
        butTongVienPhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTongVienPhiActionPerformed(evt);
            }
        });

        butTimBN.setText("Tim Benh Nhan");
        butTimBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTimBNActionPerformed(evt);
            }
        });

        butDSBNNgoai.setText("Xuat DS BNNT");
        butDSBNNgoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDSBNNgoaiActionPerformed(evt);
            }
        });

        butDocFile.setText("Doc File");
        butDocFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDocFileActionPerformed(evt);
            }
        });

        butInDS.setText("In Danh Sach");
        butInDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butInDSActionPerformed(evt);
            }
        });

        butXoa.setText("Xoa");
        butXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(butThemMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butInDS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(butTimBN, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(butDocFile, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                        .addComponent(butDSBNNgoai, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(butXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butTongVienPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTongVP, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butTimBN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butDSBNNgoai, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butDocFile, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butTongVienPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTongVP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butInDS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butThemMoiActionPerformed
        // TODO add your handling code here:
        if (comboBN.getSelectedIndex() == 0) {
            BenhNhan bnngoai = nhapBNNgoai();
            dsbn.themVaoDS(bnngoai);
            themVaoTable(bnngoai);
        } else {
            BenhNhan bnnoi = nhapBNNoi();
            dsbn.themVaoDS(bnnoi);
            themVaoTable(bnnoi);
        }
    }//GEN-LAST:event_butThemMoiActionPerformed

    private void butTimBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTimBNActionPerformed
        // TODO add your handling code here:
        BenhNhan bn = dsbn.timBN(txtMaBN.getText());
        if (bn != null) {
            xoaBang();
            themVaoTable(bn);
        } else {
            JOptionPane.showMessageDialog(null, "Tim kiem that bai!!");
        }

    }//GEN-LAST:event_butTimBNActionPerformed

    private void butDocFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDocFileActionPerformed
        try {
            // TODO add your handling code here:
            FileReader fr = new FileReader("input.txt");
            BufferedReader br = new BufferedReader(fr);
            String line = "";
            while (true) {
                line = br.readLine();
                if (line == null) {
                    break;
                }
                String st[] = line.split(",");
                String maBN = st[0];
                String hoTen = st[1];
                Date ngayVV = chuyenChuoiThanhNgay(st[2]);
                double tienThuoc = Double.parseDouble(st[3]);
                double phiKham = Double.parseDouble(st[4]);
                double phiXN = Double.parseDouble(st[5]);
                double phiNgay = Double.parseDouble(st[6]);
                Date ngayRV = chuyenChuoiThanhNgay(st[7]);

                if (phiXN == 0) {
                  BNNoiTru noiTru=new BNNoiTru(phiNgay, ngayRV, maBN, hoTen, ngayVV, tienThuoc);
                  dsbn.themVaoDS(noiTru);

                } else {
                    BNNgoaiTru bnnt = new BNNgoaiTru(phiKham, phiXN, maBN, hoTen, ngayVV, tienThuoc);
                    dsbn.themVaoDS(bnnt);
                }
            }
            fr.close();
            br.close();
        } catch (IOException ex) {
            Logger.getLogger(QuanLiBN.class.getName()).log(Level.SEVERE, null, ex);
        }
        napDuLieuChoTable();
    }//GEN-LAST:event_butDocFileActionPerformed

    private void butInDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butInDSActionPerformed
        // TODO add your handling code here:
        xoaBang();
        for (BenhNhan bn : dsbn.arr) {
            themVaoTable(bn);
        }
    }//GEN-LAST:event_butInDSActionPerformed

    private void butDSBNNgoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDSBNNgoaiActionPerformed
        // TODO add your handling code here:
        xoaBang();
        for (BenhNhan benhNhan : dsbn.dsBNNT()) {
            themVaoTable(benhNhan);
        }
    }//GEN-LAST:event_butDSBNNgoaiActionPerformed

    private void butTongVienPhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTongVienPhiActionPerformed
        // TODO add your handling code here:
        for (BenhNhan benhNhan : dsbn.arr) {
            txtTongVP.setText(String.valueOf(dsbn.TongVienPhi()));
        }
    }//GEN-LAST:event_butTongVienPhiActionPerformed

    private void butXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butXoaActionPerformed
        // TODO add your handling code here:
       
       if(dsbn.xoaTruocNgayChiDinh(txtNgayRV.getText())) {
           napDuLieuChoTable();
       } else {
           JOptionPane.showMessageDialog(null,  "Xoa khong thanh cong!!");
       }
        
    }//GEN-LAST:event_butXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLiBN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLiBN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLiBN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLiBN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLiBN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butDSBNNgoai;
    private javax.swing.JButton butDocFile;
    private javax.swing.JButton butInDS;
    private javax.swing.JButton butThemMoi;
    private javax.swing.JButton butTimBN;
    private javax.swing.JButton butTongVienPhi;
    private javax.swing.JButton butXoa;
    private javax.swing.JComboBox<String> comboBN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaBN;
    private javax.swing.JTextField txtNgayRV;
    private javax.swing.JTextField txtNgayVV;
    private javax.swing.JTextField txtPhiKham;
    private javax.swing.JTextField txtPhiNgay;
    private javax.swing.JTextField txtPhiXN;
    private javax.swing.JTextField txtTienThuoc;
    private javax.swing.JTextField txtTongVP;
    // End of variables declaration//GEN-END:variables

    private void myInit() {
        dsbn = new DSBenhNhan();
        model = (DefaultTableModel) jTable1.getModel();
        jTable1.setModel(model);
    }

    private Date chuyenChuoiThanhNgay(String text) {
        try {
            return new SimpleDateFormat("dd/MM/yy").parse(text);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        return null;
    }
    private String chuyenNgayThanhChuoi(Date d) {
        return new SimpleDateFormat("dd/MM/yy").format(d);
    }

    private void themVaoTable(BenhNhan bn) {
        if (bn instanceof BNNgoaiTru) {
            model.addRow(new Object[]{bn.getMa(), bn.getHoTen(), chuyenNgayThanhChuoi(bn.getNgayVao()), bn.getTienThuoc(), ((BNNgoaiTru) bn).getPhiKham(),
                ((BNNgoaiTru) bn).getPhiXetNghiem(), "", "", ((BNNgoaiTru) bn).vienPhi()});
        } else {
            BNNoiTru bnnoi = (BNNoiTru) bn;
            model.addRow(new Object[]{bnnoi.getMa(), bnnoi.getHoTen(), chuyenNgayThanhChuoi(bnnoi.getNgayVao()), bnnoi.getTienThuoc(), "", "", bnnoi.getPhiNgay(),
                chuyenNgayThanhChuoi(bnnoi.getNgayRaVien()), bnnoi.vienPhi()});
        }
    }

    public void xoaBang() {
        for (int i = jTable1.getRowCount(); i > 0; i--) {
            model.removeRow(i - 1);
        }
    }
    public void napDuLieuChoTable(){
        xoaBang();
        for (BenhNhan bn : dsbn.arr) {
            themVaoTable(bn);
        }
    }
}
