/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dethi2_gui;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FORMAI
 */
public class QLKS extends javax.swing.JFrame {

    /**
     * Creates new form QLKS
     */
    DSPhong dsp;
    DefaultTableModel model;
    DecimalFormat df = new DecimalFormat("#,###,###.0");
    public QLKS() {
        initComponents();
        myInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaP = new javax.swing.JTextField();
        txtHangP = new javax.swing.JTextField();
        txtNgayThue = new javax.swing.JTextField();
        txtTraNgay = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        txtSoGiuong = new javax.swing.JTextField();
        txtSoGhe = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        buttThemPhong = new javax.swing.JButton();
        buttXoaPhong = new javax.swing.JButton();
        buttCapNhat = new javax.swing.JButton();
        buttDocFile = new javax.swing.JButton();
        buttTongTien = new javax.swing.JButton();
        txtTongTien = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MãP");

        jLabel2.setText("HạngP");

        jLabel3.setText("Đơn Giá");

        jLabel4.setText("Ngày Thuê");

        jLabel5.setText("So Ghe");

        jLabel6.setText("So Giuong");

        jLabel7.setText("Ngày Trả");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phong Ngu", "Phong Hop", " " }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã P", "Hạng P", "Ngày Thuê", "Ngày Trả", "Đơn Giá", "So Giuong", "So Ghe", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        buttThemPhong.setText("Thêm phòng");
        buttThemPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttThemPhongActionPerformed(evt);
            }
        });

        buttXoaPhong.setText("Xóa Phòng");
        buttXoaPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttXoaPhongActionPerformed(evt);
            }
        });

        buttCapNhat.setText("Cập nhật");
        buttCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttCapNhatActionPerformed(evt);
            }
        });

        buttDocFile.setText("Đọc file");
        buttDocFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttDocFileActionPerformed(evt);
            }
        });

        buttTongTien.setText("Tổng tiền");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(buttThemPhong)
                .addGap(57, 57, 57)
                .addComponent(buttXoaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(buttCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttDocFile, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttThemPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttXoaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttDocFile, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMaP, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtHangP, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNgayThue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTraNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSoGiuong, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSoGhe, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(42, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHangP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTraNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoGiuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoGhe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttThemPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttThemPhongActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedIndex()==0) {
            PhongNgu pn = nhapPhongNgu();
            
            themVaoTable(pn);
        } else {
            PhongHop ph= nhapPhongHop();
            themVaoTable(ph);
        }
    }//GEN-LAST:event_buttThemPhongActionPerformed

    private void buttXoaPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttXoaPhongActionPerformed
        // TODO add your handling code here:
        
        try {
            if(dsp.xoaTheoMaPhong(txtMaP.getText())) {
            napDuLieuChoTable();
        } else {
            JOptionPane.showMessageDialog(null, "Xoa khong thanh cong");
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ban chua nhap Ma phong!!");
        }
    }//GEN-LAST:event_buttXoaPhongActionPerformed

    private void buttDocFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttDocFileActionPerformed
        
        
//        try {
//            // TODO add your handling code here:
//            FileReader fr= new FileReader("input.txt");
//            BufferedReader br= new BufferedReader(fr);
//            String line="";
//            while(true) {
//            line=br.readLine();
//            if(line==null) break;
//            String st[]=line.split(",");
//            String maP=st[0];
//            String hangP=st[1];
//            Date thue=chuyenChuoiThanhNgay(st[2]);
//            Date tra=chuyenChuoiThanhNgay(st[3]);
//            double donGia=Double.parseDouble(st[4]);
//            int soGiuong=Integer.parseInt(st[5]);
//            int soGh=Integer.parseInt(st[6]);
//            if(soGh==0) {
//                PhongNgu pn= new PhongNgu(soGiuong, maP, hangP, thue, tra, donGia);
//                dsp.themVaoDS(pn);
//                themVaoTable(pn);
//            } else {
//                PhongHop ph= new PhongHop(soGh, maP, hangP, thue, tra, donGia);
//                dsp.themVaoDS(ph);
//                themVaoTable(ph);
//            }
//            }
//            fr.close();
//            br.close();
//        } catch (IOException ex) {
//            Logger.getLogger(QLKS.class.getName()).log(Level.SEVERE, null, ex);
//        }
        int i=JOptionPane.showConfirmDialog(null, "Ban Co Muon Doc File?", "Thong bao", JOptionPane.YES_NO_OPTION);
        if(i==0) {
            try {
            // TODO add your handling code here:
            FileReader fr= new FileReader("input.txt");
            BufferedReader br= new BufferedReader(fr);
            String line="";
            while(true) {
            line=br.readLine();
            if(line==null) break;
            String st[]=line.split(",");
            String maP=st[0];
            String hangP=st[1];
            Date thue=chuyenChuoiThanhNgay(st[2]);
            Date tra=chuyenChuoiThanhNgay(st[3]);
            double donGia=Double.parseDouble(st[4]);
            int soGiuong=Integer.parseInt(st[5]);
            int soGh=Integer.parseInt(st[6]);
            if(soGh==0) {
                PhongNgu pn= new PhongNgu(soGiuong, maP, hangP, thue, tra, donGia);
                dsp.themVaoDS(pn);
                themVaoTable(pn);
            } else {
                PhongHop ph= new PhongHop(soGh, maP, hangP, thue, tra, donGia);
                dsp.themVaoDS(ph);
                themVaoTable(ph);
            }
            }
            fr.close();
            br.close();
        } catch (IOException ex) {
            Logger.getLogger(QLKS.class.getName()).log(Level.SEVERE, null, ex);
        }
        } 
    }//GEN-LAST:event_buttDocFileActionPerformed

    private void buttCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttCapNhatActionPerformed
        // TODO add your handling code here:
        Phong p= dsp.timP(txtMaP.getText());
        
        if(p!=null) {
//           int i=jTable1.getSelectedRow();
//           model.setValueAt(txtMaP.getText(), i, 0);
//           model.setValueAt(txtHangP.getText(), i, 1);
//           model.setValueAt(txtNgayThue.getText(), i, 2);
//           model.setValueAt(txtTraNgay.getText(), i, 3);
//           model.setValueAt(txtDonGia.getText(), i, 4);
//           model.setValueAt(txtSoGiuong.getText(), i, 5);
//           model.setValueAt(txtSoGhe.getText(), i, 6);
            xoaBang();
            themVaoTable(p);
            
            }
        
    }//GEN-LAST:event_buttCapNhatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLKS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLKS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLKS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLKS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLKS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttCapNhat;
    private javax.swing.JButton buttDocFile;
    private javax.swing.JButton buttThemPhong;
    private javax.swing.JButton buttTongTien;
    private javax.swing.JButton buttXoaPhong;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtHangP;
    private javax.swing.JTextField txtMaP;
    private javax.swing.JTextField txtNgayThue;
    private javax.swing.JTextField txtSoGhe;
    private javax.swing.JTextField txtSoGiuong;
    private javax.swing.JTextField txtTongTien;
    private javax.swing.JTextField txtTraNgay;
    // End of variables declaration//GEN-END:variables

    public void themVaoTable(Phong p) {
        if(p instanceof PhongNgu) {
            model.addRow(new Object[]{p.getMaP(),p.getHangP(),p.getNgayThue(),p.getNgayTra(),p.getDonGia(),((PhongNgu) p).getSoGiuong(),"",df.format(p.tinhTienThue())});
        } else {
            PhongHop ph= (PhongHop) p;
            model.addRow(new Object[]{ph.getMaP(),ph.getHangP(),ph.getNgayThue(),ph.getNgayTra(),ph.getDonGia(),"",ph.getSoGhe(),df.format(ph.tinhTienThue())});
        }
    }
    public void xoaBang() {
        for (int i = jTable1.getRowCount(); i > 0; i--) {
            model.removeRow(i-1);
        }
    }
    public void napDuLieuChoTable() {
        xoaBang();
        for (Phong phong : dsp.arr) {
            themVaoTable(phong);
        }
    }
    public PhongNgu nhapPhongNgu() {
        String maP=txtMaP.getText();
        String hangP=txtHangP.getText();
        Date thue=chuyenChuoiThanhNgay(txtNgayThue.getText());
        Date tra=chuyenChuoiThanhNgay(txtTraNgay.getText());
        Double donGia=Double.parseDouble(txtDonGia.getText());
        int soGiuong=Integer.parseInt(txtSoGiuong.getText());
        PhongNgu pn= new PhongNgu(soGiuong, maP, hangP, thue, tra, donGia);
        return pn;
    }
    public PhongHop nhapPhongHop() {
        String maP=txtMaP.getText();
        String hangP=txtHangP.getText();
        Date thue=chuyenChuoiThanhNgay(txtNgayThue.getText());
        Date tra=chuyenChuoiThanhNgay(txtTraNgay.getText());
        Double donGia=Double.parseDouble(txtDonGia.getText());
        int soGhe=Integer.parseInt(txtSoGhe.getText());
        PhongHop ph= new PhongHop(soGhe, maP, hangP, thue, tra, donGia);
        return ph;
    }
    private void myInit() {
            dsp= new DSPhong();
            model= (DefaultTableModel) jTable1.getModel();
            jTable1.setModel(model);
    }
    public Date chuyenChuoiThanhNgay(String dts) {
        try {
            return new SimpleDateFormat("dd/MM/yy").parse(dts);
        } catch (ParseException ex) {
            Logger.getLogger(QLKS.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    private String chuyenNgayThanhChuoi(Date d) {
        return new SimpleDateFormat("dd/MM/yy").format(d);
    }
}
