/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package learngui;

import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author FORMAI
 */
public class List_learn extends javax.swing.JFrame {
    DefaultListModel modelLeft,modelRight;

    /**
     * Creates new form List_learn
     */
    public List_learn() {
        initComponents();
        myInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listLeft = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listRight = new javax.swing.JList<>();
        butLtoR = new javax.swing.JButton();
        butAllLtoR = new javax.swing.JButton();
        butAllRtoLeft = new javax.swing.JButton();
        butRtoL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listLeftMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listLeft);

        listRight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listRightMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listRight);

        butLtoR.setText(">");
        butLtoR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLtoRActionPerformed(evt);
            }
        });

        butAllLtoR.setText(">>");
        butAllLtoR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAllLtoRActionPerformed(evt);
            }
        });

        butAllRtoLeft.setText("<<");
        butAllRtoLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAllRtoLeftActionPerformed(evt);
            }
        });

        butRtoL.setText("<");
        butRtoL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRtoLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(butAllLtoR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butAllRtoLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butRtoL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butLtoR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(butLtoR, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(butAllLtoR, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(butRtoL, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(butAllRtoLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butLtoRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLtoRActionPerformed
        // TODO add your handling code here:
        diChuyen(modelLeft, modelRight, listLeft, listRight);
    }//GEN-LAST:event_butLtoRActionPerformed

    private void butRtoLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRtoLActionPerformed
        // TODO add your handling code here:
        diChuyen(modelRight, modelLeft, listRight, listLeft);
    }//GEN-LAST:event_butRtoLActionPerformed

    private void butAllLtoRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAllLtoRActionPerformed
        // TODO add your handling code here:
        diChuyenAll(modelLeft, modelRight, listLeft, listRight);
    }//GEN-LAST:event_butAllLtoRActionPerformed

    private void butAllRtoLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAllRtoLeftActionPerformed
        // TODO add your handling code here:
        diChuyenAll(modelRight, modelLeft, listRight, listLeft);
    }//GEN-LAST:event_butAllRtoLeftActionPerformed

    private void listLeftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listLeftMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2) {
            diChuyen(modelLeft, modelRight, listLeft, listRight);
        }
    }//GEN-LAST:event_listLeftMouseClicked

    private void listRightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listRightMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2) {
            diChuyen(modelRight, modelLeft, listRight, listLeft);
        }
    }//GEN-LAST:event_listRightMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(List_learn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(List_learn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(List_learn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(List_learn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new List_learn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAllLtoR;
    private javax.swing.JButton butAllRtoLeft;
    private javax.swing.JButton butLtoR;
    private javax.swing.JButton butRtoL;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listLeft;
    private javax.swing.JList<String> listRight;
    // End of variables declaration//GEN-END:variables

    private void myInit() {
        setLocationRelativeTo(null);
        modelLeft = new DefaultListModel();
        modelRight = new DefaultListModel();
        listLeft.setModel(modelLeft);
        listRight.setModel(modelRight);
        for (int i = 0; i < 10; i++) {
            modelLeft.addElement("Phan tu thu "+(i+1));
        }
    }
    public void diChuyen(DefaultListModel modelGoc, DefaultListModel modelDen, JList listGoc,JList listDen) {
        int i=listGoc.getSelectedIndex();//Chon 1 item ben list Goc
        while(i!=-1) { //i!=-1 la co chon
            //them vao model Den 1 item lay tu model Goc tai vi tri i
            modelDen.addElement(modelGoc.getElementAt(i));
            //phai xoa item o model Goc
            modelGoc.removeElementAt(i);
            //muon chon item tiep theo thi
            i=listGoc.getSelectedIndex();
        }
    }
    public void diChuyenAll(DefaultListModel modelGoc, DefaultListModel modelDen, JList listGoc,JList listDen) {
    
        for (int i = 0; i < modelGoc.getSize(); i++) {
            modelDen.addElement(modelGoc.getElementAt(i));
        }
        modelGoc.removeAllElements();
    }
    
}
