/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dethi4;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FORMAI
 */
public class QuanLiBN extends javax.swing.JFrame {

    /**
     * Creates new form QuanLiBN
     */
    DSBENHNHAN dsbn;
    DefaultTableModel model;
    DecimalFormat df = new DecimalFormat("#,###,###.0");
    int i;

    public QuanLiBN() {

        initComponents();
        myInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaBN = new javax.swing.JTextField();
        txtNgayNV = new javax.swing.JTextField();
        txtMAYT = new javax.swing.JTextField();
        txtMAXH = new javax.swing.JTextField();
        txtNgayRV = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txtPhongYC = new javax.swing.JTextField();
        comBN = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        butDocFile = new javax.swing.JButton();
        butThemMOi = new javax.swing.JButton();
        butInDS = new javax.swing.JButton();
        butTimKiem = new javax.swing.JButton();
        butXoa = new javax.swing.JButton();
        butCapNhat = new javax.swing.JButton();
        butXuatFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã BN");

        jLabel2.setText("Ngày NV");

        jLabel3.setText("Mã BHYT");

        jLabel4.setText("Mã BHXH");

        jLabel5.setText("Ngày RV");

        jLabel6.setText("Họ Tên");

        jLabel7.setText("Phòng Yêu Cầu");

        txtMAYT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMAYTActionPerformed(evt);
            }
        });

        txtNgayRV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayRVActionPerformed(evt);
            }
        });

        comBN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BHYT", "BHXH", " " }));
        comBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(comBN, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMAYT, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNgayNV, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaBN, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNgayRV, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtMAXH, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPhongYC, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtHoTen)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgayNV)
                            .addComponent(txtNgayRV))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(comBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMAYT)
                    .addComponent(txtMAXH))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhongYC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MaBN", "HoTen", "NgayNV", "NgayRV", "Ma BHYT", "Ma BHXH", "YC Phong", "Viện Phí"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        butDocFile.setText("Đọc File");
        butDocFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDocFileActionPerformed(evt);
            }
        });

        butThemMOi.setText("Thêm Mới");
        butThemMOi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butThemMOiActionPerformed(evt);
            }
        });

        butInDS.setText("In DS");
        butInDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butInDSActionPerformed(evt);
            }
        });

        butTimKiem.setText("Tìm kiếm");
        butTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTimKiemActionPerformed(evt);
            }
        });

        butXoa.setText("Xóa BN");
        butXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butXoaActionPerformed(evt);
            }
        });

        butCapNhat.setText("Cập nhật");
        butCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCapNhatActionPerformed(evt);
            }
        });

        butXuatFile.setText("Xuất File");
        butXuatFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butXuatFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 899, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(butDocFile, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(butThemMOi, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(butInDS, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(butTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(butXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(butCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(butXuatFile, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(400, 400, 400))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butDocFile, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butThemMOi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butInDS, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(butXuatFile, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMAYTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMAYTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMAYTActionPerformed

    private void txtNgayRVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayRVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayRVActionPerformed

    private void comBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comBNActionPerformed
    public BAOHIEMYTE nhapBHYT() {
        String maBN = txtMaBN.getText();
        String hoTen = txtHoTen.getText();
        Date ngayVao = chuyenChuoiThanhNgay(txtNgayNV.getText());
        Date ngayRa = chuyenChuoiThanhNgay(txtNgayRV.getText());
        String maYT = txtMAYT.getText();
        String yC = txtPhongYC.getText();
        BAOHIEMYTE bhyt = new BAOHIEMYTE(maYT, maBN, hoTen, ngayRa, ngayRa, rootPaneCheckingEnabled);
        return bhyt;
    }

    public BAOHIEMXAHOI nhapBHXH() {
        String maBN = txtMaBN.getText();
        String hoTen = txtHoTen.getText();
        Date ngayVao = chuyenChuoiThanhNgay(txtNgayNV.getText());
        Date ngayRa = chuyenChuoiThanhNgay(txtNgayRV.getText());
        String maXH = txtMAXH.getText();
        String yC = txtPhongYC.getText();
        BAOHIEMXAHOI bhxh = new BAOHIEMXAHOI(maXH, maBN, hoTen, ngayRa, ngayRa, rootPaneCheckingEnabled);
        return bhxh;
    }
    private void butDocFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDocFileActionPerformed
        try {
            // TODO add your handling code here:
            FileReader fr = new FileReader("input.txt");
            BufferedReader br = new BufferedReader(fr);
            String line = "";
            while (true) {
                line = br.readLine();
                if (line == null) {
                    break;
                }
                String st[] = line.split(",");
                String maBN = st[0];
                String hoTen = st[1];
                Date ngayVao = chuyenChuoiThanhNgay(st[2]);
                Date ngayRa = chuyenChuoiThanhNgay(st[3]);
                String BHYT = st[4];
                String BHXH = st[5];
                boolean phongYC = (st[6].equalsIgnoreCase("0") ? false : true);
                if (BHXH.equals("0")) {
                    BAOHIEMYTE bhyt = new BAOHIEMYTE(BHYT, maBN, hoTen, ngayVao, ngayRa, phongYC);
                    dsbn.themVaoDS(bhyt);
                    themVaoTable(bhyt);
                } else {
                    BAOHIEMXAHOI bhxh = new BAOHIEMXAHOI(BHXH, maBN, hoTen, ngayVao, ngayRa, phongYC);
                    dsbn.themVaoDS(bhxh);
                    themVaoTable(bhxh);
                }
            }
            fr.close();
            br.close();
        } catch (IOException ex) {
            Logger.getLogger(QuanLiBN.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_butDocFileActionPerformed

    private void butThemMOiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butThemMOiActionPerformed
        // TODO add your handling code here:
        if (comBN.getSelectedIndex() == 0) {
            BenhNhan bn = nhapBHYT();
            themVaoTable(bn);
            dsbn.themVaoDS(bn);
        } else {
            BenhNhan bn2 = nhapBHXH();
            themVaoTable(bn2);
            dsbn.themVaoDS(bn2);
        }

    }//GEN-LAST:event_butThemMOiActionPerformed

    private void butInDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butInDSActionPerformed
        // TODO add your handling code here:
        xoaBang();
        for (BenhNhan bn : dsbn.arr) {
            themVaoTable(bn);
        }
    }//GEN-LAST:event_butInDSActionPerformed

    private void butTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTimKiemActionPerformed
        // TODO add your handling code here:
        BenhNhan bn = dsbn.timBN(txtMaBN.getText());

        if (bn != null) {
            xoaBang();
            themVaoTable(bn);
        } else {
            JOptionPane.showMessageDialog(null, "Tim kiem that bai!!");
        }
    }//GEN-LAST:event_butTimKiemActionPerformed

    private void butXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butXoaActionPerformed
        // TODO add your handling code here:
        xoaBang();
        dsbn.xoaBN(txtMaBN.getText());
        for (BenhNhan benhNhan : dsbn.arr) {
            themVaoTable(benhNhan);
        }
    }//GEN-LAST:event_butXoaActionPerformed

    private void butCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCapNhatActionPerformed
        // TODO add your handling code here:
        //Cap nhat jatbale: hien thi du lieu
//        model.setValueAt(txtMaBN.getText(), i, 0);
//        model.setValueAt(txtHoTen.getText(), i, 1);
//        model.setValueAt(txtNgayNV.getText(), i, 2);
//        model.setValueAt(txtNgayRV.getText(), i, 3);
//        model.setValueAt(txtMAYT.getText(), i, 4);
//        model.setValueAt(txtMAXH.getText(), i, 5);
//        model.setValueAt(txtPhongYC.getText(), i, 6);
////        model.setValueAt(comBN.getSelectedItem(), i, 7);
        
    

        int j=jTable1.getSelectedRow();
        if(j<0) JOptionPane.showMessageDialog(null, "Ban chua chon dong de cap nhat!!");
        
        int i = jTable1.getSelectedRow();
        if(i>0) {
            BenhNhan bn = dsbn.arr.get(i);
            if(bn instanceof BAOHIEMYTE){
            bn.setMaBN(txtMaBN.getText());
            bn.setHoTen(txtHoTen.getText());
            bn.setNgayNV(chuyenChuoiThanhNgay(txtNgayNV.getText()));
            bn.setNgayRV(chuyenChuoiThanhNgay(txtNgayRV.getText()));
            ((BAOHIEMYTE) bn).setMaBHYT(txtMAYT.getText());
            bn.setPhongYC(rootPaneCheckingEnabled);
                    } else {
            BAOHIEMXAHOI xh=(BAOHIEMXAHOI) bn;
            xh.setMaBN(txtMaBN.getText());
            xh.setHoTen(txtHoTen.getText());
            xh.setNgayNV(chuyenChuoiThanhNgay(txtNgayNV.getText()));
            xh.setNgayRV(chuyenChuoiThanhNgay(txtNgayRV.getText()));
            xh.setMaBHXH(txtMAXH.getText());
            bn.setPhongYC(rootPaneCheckingEnabled);
            }
        }
    }//GEN-LAST:event_butCapNhatActionPerformed

    private void butXuatFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butXuatFileActionPerformed
        try {
            // TODO add your handling code here:
            FileWriter fw = new FileWriter(new File("output.txt"));
            BufferedWriter bw = new BufferedWriter(fw);
            for (BenhNhan bn : dsbn.arr) {
                bw.write(bn.toString());
                bw.newLine();
            }
            JOptionPane.showMessageDialog(null, "GHi file thanh cong!!");

            bw.close();
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(QuanLiBN.class.getName()).log(Level.SEVERE, null, ex);
        }
//           if(bn instanceof BAOHIEMYTE) {
//                    fw.write(bn.getMaBN()+"\t"+bn.getHoTen()+"\t"+chuyenNgayThanhChuoi(bn.getNgayNV())+"\t"+chuyenNgayThanhChuoi(bn.getNgayRV())+"\t"+((BAOHIEMYTE) bn).getMaBHYT()+"\t"+"\t"+df.format(bn.tinhVienPhi())+"\n");
//                } else {
//                    BAOHIEMXAHOI xh=(BAOHIEMXAHOI) bn;
//                    fw.write(xh.getMaBN()+"\t"+xh.getHoTen()+"\t"+"\t"+chuyenNgayThanhChuoi(xh.getNgayNV())+"\t"+chuyenNgayThanhChuoi(xh.getNgayRV())+"\t"+"\t"+xh.getMaBHXH()+"\t"+df.format(xh.tinhVienPhi())+"\n");
//                }
    }//GEN-LAST:event_butXuatFileActionPerformed
    public String chuyenBooleanThanhChuoi(boolean yc) {
        if (yc) {
            return "Co";
        }
        return "Khong";
    }
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        i = jTable1.getSelectedRow();
        if (evt.getClickCount() == 2) {
            txtMaBN.setText(model.getValueAt(i, 0).toString());
            txtHoTen.setText(model.getValueAt(i, 1).toString());
            txtNgayNV.setText(model.getValueAt(i, 2).toString());
            txtNgayRV.setText(model.getValueAt(i, 3).toString());
            txtMAYT.setText(model.getValueAt(i, 4).toString());
            txtMAXH.setText(model.getValueAt(i, 5).toString());
            txtPhongYC.setText(model.getValueAt(i, 6).toString());
      
            comBN.setSelectedItem(model.getValueAt(i, 7));
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLiBN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLiBN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLiBN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLiBN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLiBN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butCapNhat;
    private javax.swing.JButton butDocFile;
    private javax.swing.JButton butInDS;
    private javax.swing.JButton butThemMOi;
    private javax.swing.JButton butTimKiem;
    private javax.swing.JButton butXoa;
    private javax.swing.JButton butXuatFile;
    private javax.swing.JComboBox<String> comBN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMAXH;
    private javax.swing.JTextField txtMAYT;
    private javax.swing.JTextField txtMaBN;
    private javax.swing.JTextField txtNgayNV;
    private javax.swing.JTextField txtNgayRV;
    private javax.swing.JTextField txtPhongYC;
    // End of variables declaration//GEN-END:variables

    private Date chuyenChuoiThanhNgay(String nl) {
        try {
            return new SimpleDateFormat("dd/MM/yy").parse(nl);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        return null;
    }

    private String chuyenNgayThanhChuoi(Date d) {
        return new SimpleDateFormat("dd/MM/yy").format(d);
    }

    public void themVaoTable(BenhNhan bn) {
        if (bn instanceof BAOHIEMYTE) {
            model.addRow(new Object[]{bn.getMaBN(), bn.getHoTen(), chuyenNgayThanhChuoi(bn.getNgayNV()), chuyenNgayThanhChuoi(bn.getNgayRV()), ((BAOHIEMYTE) bn).getMaBHYT(), "",
                chuyenBooleanThanhChuoi(bn.isPhongYC()), df.format(bn.tinhVienPhi())});
        } else {
            BAOHIEMXAHOI xh = (BAOHIEMXAHOI) bn;
            model.addRow(new Object[]{xh.getMaBN(), xh.getHoTen(), chuyenNgayThanhChuoi(xh.getNgayNV()), chuyenNgayThanhChuoi(xh.getNgayRV()), "", xh.getMaBHXH(),
                chuyenBooleanThanhChuoi(xh.isPhongYC()), df.format(xh.tinhVienPhi())});

        }
    }

    private void myInit() {
        dsbn = new DSBENHNHAN();
        setLocationRelativeTo(null);
        model = (DefaultTableModel) jTable1.getModel();
        jTable1.setModel(model);
    }

    private void xoaBang() {
        for (int i = jTable1.getRowCount(); i > 0; i--) {
            model.removeRow(i - 1);
        }
    }

}
